Player movement
Questinator/Typing-Game-2024 pull request #6
Opened 2024-03-20 17:11 UTC by 1095795

rotation works properly gravity also works, needs a CharacterController to work.

2024-03-26 20:37 UTC, ilhs1096069 requested changes
Good code just some changes needed here and there

2024-03-26 20:37 UTC, ilhs1096069 commented on Assets/Scripts/PlayerMovementScript.cs
Explained this earlier but basically make sure any public variables are instead `[SerializedField]` private variables

2024-03-26 20:37 UTC, ilhs1096069 commented on Assets/Scripts/PlayerMovementScript.cs
> +    public float gravityMultiplyer = 3.0f;
you spelt multiplier wrong :)

2024-03-26 20:37 UTC, ilhs1096069 commented on Assets/Scripts/PlayerMovementScript.cs
> +    public float gravityMultiplyer = 3.0f;
also why is this public but you have a serialized field down below?

2024-03-26 20:37 UTC, ilhs1096069 commented on Assets/Scripts/PlayerMovementScript.cs
> +    void Update()
I'd recommend changing this into a FixedUpdate() just to make sure the player isn't moving faster or slower depending on frame rate. Make sure all references to Time.deltaTime are changed to Time.fixedDeltaTime

2024-03-26 20:37 UTC, ilhs1096069 commented on Assets/Scripts/PlayerMovementScript.cs
> +        _direction = new Vector3(_input.x, 0f, _input.y);
We should probably in the future make sure the direction is based on the camera so pressing forward moves you away from the camera

2024-05-02 20:25 UTC, ilhs1096069 commented
Did some cleanup to the code since Nathan didn't

2024-05-02 20:25 UTC, roguefirework approved these changes
Looks good to me

2024-05-02 20:25 UTC, ilhs1096069 approved these changes

2024-05-02 20:25 UTC, merged